export const tempCandidates = [
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV1',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Donald Trump',
    url: 'trump2020.com',
    location: 'United States',
    state: 'Active',
    votes: '0',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Bernie Sanders',
    url: 'berniesanders.com',
    location: 'United States',
    state: 'Active',
    votes: '125',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV3',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Chad Racelis',
    url: 'chadracelis.com',
    location: 'United States',
    state: 'Active',
    votes: '100',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV4',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Ben Piette',
    url: 'benpiette.com',
    location: 'France',
    state: 'Active',
    votes: '333',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV5',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Famous Amos',
    url: 'famousamos.com',
    location: 'Trinidad',
    state: 'Active',
    votes: '420',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV6',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Houston Mike',
    url: 'houstonmike.com',
    location: 'United States',
    state: 'Active',
    votes: '40',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV7',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Rong Chen',
    url: 'ronchen.com',
    location: 'China',
    state: 'Active',
    votes: '10000',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV8',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Donnie Bullers',
    url: 'donniebullers.com',
    location: 'United States',
    state: 'Active',
    votes: '200',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV9',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Martin Knight',
    url: 'martinknight.com',
    location: 'United Kingdom',
    state: 'Active',
    votes: '155',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
  {
    code: '123456789',
    cid: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV10',
    did: 'iTgmaqaMpMj46MW3GCU2h7bPaytwuvQrV2',
    nickname: 'Clarence Liu',
    url: 'clarencelui.com',
    location: 'United States',
    state: 'Active',
    votes: '10',
    registerheight: 1,
    cancelheight: 2,
    index: 3
  },
]
